/*
 * Copyright (C) 2006, 2007, 2008, 2009 Apple Inc.  All rights reserved.
 *
 * Redistribution and use in source and binary forms, with or without
 * modification, are permitted provided that the following conditions
 * are met:
 * 1. Redistributions of source code must retain the above copyright
 *    notice, this list of conditions and the following disclaimer.
 * 2. Redistributions in binary form must reproduce the above copyright
 *    notice, this list of conditions and the following disclaimer in the
 *    documentation and/or other materials provided with the distribution.
 *
 * THIS SOFTWARE IS PROVIDED BY APPLE COMPUTER, INC. ``AS IS'' AND ANY
 * EXPRESS OR IMPLIED WARRANTIES, INCLUDING, BUT NOT LIMITED TO, THE
 * IMPLIED WARRANTIES OF MERCHANTABILITY AND FITNESS FOR A PARTICULAR
 * PURPOSE ARE DISCLAIMED.  IN NO EVENT SHALL APPLE COMPUTER, INC. OR
 * CONTRIBUTORS BE LIABLE FOR ANY DIRECT, INDIRECT, INCIDENTAL, SPECIAL,
 * EXEMPLARY, OR CONSEQUENTIAL DAMAGES (INCLUDING, BUT NOT LIMITED TO,
 * PROCUREMENT OF SUBSTITUTE GOODS OR SERVICES; LOSS OF USE, DATA, OR
 * PROFITS; OR BUSINESS INTERRUPTION) HOWEVER CAUSED AND ON ANY THEORY
 * OF LIABILITY, WHETHER IN CONTRACT, STRICT LIABILITY, OR TORT
 * (INCLUDING NEGLIGENCE OR OTHERWISE) ARISING IN ANY WAY OUT OF THE USE
 * OF THIS SOFTWARE, EVEN IF ADVISED OF THE POSSIBILITY OF SUCH DAMAGE. 
 */

#ifndef DO_NO_IMPORTS
import "oaidl.idl";
import "ocidl.idl";
import "IWebFrame.idl";
import "IWebView.idl";
#endif

interface IWebFrame;
interface IWebView;

[
    object,
    oleautomation,
    uuid(5566CB49-6E87-4075-80CE-9BAC374C52DE),
    pointer_default(unique)
]
interface IWebFrameLoadDelegatePrivate : IUnknown
{
    //- (void)webView:(WebView *)sender didFinishDocumentLoadForFrame:(WebFrame *)frame;
    HRESULT didFinishDocumentLoadForFrame([in] IWebView* sender, [in] IWebFrame* frame);

    //- (void)webView:(WebView *)sender didFirstLayoutInFrame:(WebFrame *)frame;
    HRESULT didFirstLayoutInFrame([in] IWebView* sender, [in] IWebFrame* frame);

    // Addresses 4192534.  Private API for now.
    //- (void)webView:(WebView *)sender didHandleOnloadEventsForFrame:(WebFrame *)frame;
    HRESULT didHandleOnloadEventsForFrame([in] IWebView* sender, [in] IWebFrame* frame);

    HRESULT didFirstVisuallyNonEmptyLayoutInFrame([in] IWebView* sender, [in] IWebFrame* frame);
}
