/*
 * Copyright (C) 2006 Apple Computer, Inc.
 *
 * This library is free software; you can redistribute it and/or
 * modify it under the terms of the GNU Library General Public
 * License as published by the Free Software Foundation; either
 * version 2 of the License, or (at your option) any later version.
 *
 * This library is distributed in the hope that it will be useful,
 * but WITHOUT ANY WARRANTY; without even the implied warranty of
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the GNU
 * Library General Public License for more details.
 *
 * You should have received a copy of the GNU Library General Public License
 * along with this library; see the file COPYING.LIB.  If not, write to
 * the Free Software Foundation, Inc., 51 Franklin Street, Fifth Floor,
 * Boston, MA 02110-1301, USA.
 */

[
    ConstructorConditional=DOM4_EVENTS_CONSTRUCTOR,
    ConstructorTemplate=Event
] interface UIEvent : Event {
    [InitializedByEventConstructor] readonly attribute DOMWindow view;
    [InitializedByEventConstructor] readonly attribute long detail;
    
    [ObjCLegacyUnnamedParameters] void initUIEvent([Default=Undefined] optional DOMString type, 
                                    [Default=Undefined] optional boolean canBubble, 
                                    [Default=Undefined] optional boolean cancelable, 
                                    [Default=Undefined] optional DOMWindow view, 
                                    [Default=Undefined] optional long detail);

    // extensions
    readonly attribute long                 keyCode;
    readonly attribute long                 charCode;
    readonly attribute long                 layerX;
    readonly attribute long                 layerY;
    readonly attribute long                 pageX;
    readonly attribute long                 pageY;
    readonly attribute long                 which;
};

