/*
 * Copyright (C) 2006, 2010 Apple Inc. All rights reserved.
 * Copyright (C) 2006 Samuel Weinig <sam.weinig@gmail.com>
 *
 * This library is free software; you can redistribute it and/or
 * modify it under the terms of the GNU Library General Public
 * License as published by the Free Software Foundation; either
 * version 2 of the License, or (at your option) any later version.
 *
 * This library is distributed in the hope that it will be useful,
 * but WITHOUT ANY WARRANTY; without even the implied warranty of
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the GNU
 * Library General Public License for more details.
 *
 * You should have received a copy of the GNU Library General Public License
 * along with this library; see the file COPYING.LIB.  If not, write to
 * the Free Software Foundation, Inc., 51 Franklin Street, Fifth Floor,
 * Boston, MA 02110-1301, USA.
 */

[
    CustomNamedGetter
] interface HTMLFormElement : HTMLElement {
    [Reflect=accept_charset] attribute DOMString acceptCharset;
    [Reflect, URL] attribute DOMString action;
    [Reflect] attribute DOMString autocomplete;
    [TreatNullAs=NullString] attribute DOMString enctype;
    [TreatNullAs=NullString] attribute DOMString encoding;
    [TreatNullAs=NullString] attribute DOMString method;
    [Reflect] attribute DOMString name;
    [Reflect] attribute boolean noValidate;
    [Reflect] attribute DOMString target;

    readonly attribute HTMLCollection elements;
    readonly attribute long length;

    getter Element (unsigned long index);

#if defined(LANGUAGE_JAVASCRIPT) && LANGUAGE_JAVASCRIPT
    [ImplementedAs=submitFromJavaScript] void submit();
#else
    void submit();
#endif
    void reset();
    boolean checkValidity();
};
