/*
 * Copyright (C) 2006, 2009, 2010 Apple Inc. All rights reserved.
 * Copyright (C) 2006 Samuel Weinig <sam.weinig@gmail.com>
 *
 * This library is free software; you can redistribute it and/or
 * modify it under the terms of the GNU Library General Public
 * License as published by the Free Software Foundation; either
 * version 2 of the License, or (at your option) any later version.
 *
 * This library is distributed in the hope that it will be useful,
 * but WITHOUT ANY WARRANTY; without even the implied warranty of
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the GNU
 * Library General Public License for more details.
 *
 * You should have received a copy of the GNU Library General Public License
 * along with this library; see the file COPYING.LIB.  If not, write to
 * the Free Software Foundation, Inc., 51 Franklin Street, Fifth Floor,
 * Boston, MA 02110-1301, USA.
 */

interface HTMLBodyElement : HTMLElement {
    [Reflect] attribute DOMString aLink;
    [Reflect] attribute DOMString background;
    [Reflect] attribute DOMString bgColor;
    [Reflect] attribute DOMString link;
    [Reflect] attribute DOMString text;
    [Reflect] attribute DOMString vLink;

#if !defined(LANGUAGE_OBJECTIVE_C) || !LANGUAGE_OBJECTIVE_C
    // Event handler attributes
    [NotEnumerable, JSWindowEventListener] attribute EventListener onbeforeunload;
    [NotEnumerable, JSWindowEventListener] attribute EventListener onhashchange;
    [NotEnumerable, JSWindowEventListener] attribute EventListener onmessage;
    [NotEnumerable, JSWindowEventListener] attribute EventListener onoffline;
    [NotEnumerable, JSWindowEventListener] attribute EventListener ononline;
    [NotEnumerable, JSWindowEventListener] attribute EventListener onpopstate;
    [NotEnumerable, JSWindowEventListener] attribute EventListener onresize;
    [NotEnumerable, JSWindowEventListener] attribute EventListener onstorage;
    [NotEnumerable, JSWindowEventListener] attribute EventListener onunload;

    [Conditional=ORIENTATION_EVENTS, NotEnumerable, JSWindowEventListener] attribute EventListener onorientationchange;

    // Overrides of Element attributes (with different implementation in bindings).
    [NotEnumerable, JSWindowEventListener] attribute EventListener onblur;
    [NotEnumerable, JSWindowEventListener] attribute EventListener onerror;
    [NotEnumerable, JSWindowEventListener] attribute EventListener onfocus;
    [NotEnumerable, JSWindowEventListener] attribute EventListener onload;

    // Not implemented yet.
    // [NotEnumerable, JSWindowEventListener] attribute EventListener onafterprint;
    // [NotEnumerable, JSWindowEventListener] attribute EventListener onbeforeprint;
    // [NotEnumerable, JSWindowEventListener] attribute EventListener onredo;
    // [NotEnumerable, JSWindowEventListener] attribute EventListener onundo;
#endif
};

