#!/usr/bin/perl
#
# Copyright (C) 2008 Holger Hans Peter Freyther
#
# Redistribution and use in source and binary forms, with or without
# modification, are permitted provided that the following conditions
# are met:
#
# 1.  Redistributions of source code must retain the above copyright
#     notice, this list of conditions and the following disclaimer. 
# 2.  Redistributions in binary form must reproduce the above copyright
#     notice, this list of conditions and the following disclaimer in the
#     documentation and/or other materials provided with the distribution. 
# 3.  Neither the name of Apple Computer, Inc. ("Apple") nor the names of
#     its contributors may be used to endorse or promote products derived
#     from this software without specific prior written permission. 
#
# THIS SOFTWARE IS PROVIDED BY APPLE AND ITS CONTRIBUTORS "AS IS" AND ANY
# EXPRESS OR IMPLIED WARRANTIES, INCLUDING, BUT NOT LIMITED TO, THE IMPLIED
# WARRANTIES OF MERCHANTABILITY AND FITNESS FOR A PARTICULAR PURPOSE ARE
# DISCLAIMED. IN NO EVENT SHALL APPLE OR ITS CONTRIBUTORS BE LIABLE FOR ANY
# DIRECT, INDIRECT, INCIDENTAL, SPECIAL, EXEMPLARY, OR CONSEQUENTIAL DAMAGES
# (INCLUDING, BUT NOT LIMITED TO, PROCUREMENT OF SUBSTITUTE GOODS OR SERVICES;
# LOSS OF USE, DATA, OR PROFITS; OR BUSINESS INTERRUPTION) HOWEVER CAUSED AND
# ON ANY THEORY OF LIABILITY, WHETHER IN CONTRACT, STRICT LIABILITY, OR TORT
# (INCLUDING NEGLIGENCE OR OTHERWISE) ARISING IN ANY WAY OUT OF THE USE OF
# THIS SOFTWARE, EVEN IF ADVISED OF THE POSSIBILITY OF SUCH DAMAGE.

# Regenerate WebCore/inspector/front-end/WebKit.qrc from the content of WebCore/inspector/front-end/

sub addFiles(@)
{
    my @files = @_;

    foreach $file (@files) {
        $file =~ s,Source/WebCore/inspector/front-end/,,;
        print WEBKIT_QRC "    <file>".$file . "</file>\n";
    }
}

# Setup
open(WEBKIT_QRC, ">Source/WebCore/inspector/front-end/WebKit.qrc") or die;
print WEBKIT_QRC '<!DOCTYPE RCC><RCC version="1.0">'."\n";
print WEBKIT_QRC '<qresource prefix="/webkit/inspector">'."\n";


# Directory with html and js files and the images
addFiles(<Source/WebCore/inspector/front-end/*.{*html,js,css,svg}>);
addFiles(<Source/WebCore/inspector/front-end/Images/*>);

print WEBKIT_QRC "</qresource>\n";
print WEBKIT_QRC "</RCC>\n";
close(WEBKIT_QRC);
