#!/usr/bin/perl -w

# Copyright (C) 2007 Apple Computer, Inc.  All rights reserved.
# Copyright (C) 2007 Staikos Computing Services, Inc.  <info@staikos.net>
#
# Redistribution and use in source and binary forms, with or without
# modification, are permitted provided that the following conditions
# are met:
#
# 1.  Redistributions of source code must retain the above copyright
#     notice, this list of conditions and the following disclaimer. 
# 2.  Redistributions in binary form must reproduce the above copyright
#     notice, this list of conditions and the following disclaimer in the
#     documentation and/or other materials provided with the distribution. 
# 3.  Neither the name of Apple Computer, Inc. ("Apple") nor the names of
#     its contributors may be used to endorse or promote products derived
#     from this software without specific prior written permission. 
#
# THIS SOFTWARE IS PROVIDED BY APPLE AND ITS CONTRIBUTORS "AS IS" AND ANY
# EXPRESS OR IMPLIED WARRANTIES, INCLUDING, BUT NOT LIMITED TO, THE IMPLIED
# WARRANTIES OF MERCHANTABILITY AND FITNESS FOR A PARTICULAR PURPOSE ARE
# DISCLAIMED. IN NO EVENT SHALL APPLE OR ITS CONTRIBUTORS BE LIABLE FOR ANY
# DIRECT, INDIRECT, INCIDENTAL, SPECIAL, EXEMPLARY, OR CONSEQUENTIAL DAMAGES
# (INCLUDING, BUT NOT LIMITED TO, PROCUREMENT OF SUBSTITUTE GOODS OR SERVICES;
# LOSS OF USE, DATA, OR PROFITS; OR BUSINESS INTERRUPTION) HOWEVER CAUSED AND
# ON ANY THEORY OF LIABILITY, WHETHER IN CONTRACT, STRICT LIABILITY, OR TORT
# (INCLUDING NEGLIGENCE OR OTHERWISE) ARISING IN ANY WAY OUT OF THE USE OF
# THIS SOFTWARE, EVEN IF ADVISED OF THE POSSIBILITY OF SUCH DAMAGE.

# Simplified "run" script for WebKit Open Source Project.

use strict;
use File::Spec::Functions qw/catdir/;
use File::Temp qw/tempfile/;
use FindBin;
use lib $FindBin::Bin;
use webkitdirs;

setConfiguration();
my $productDir = productDir();
my $launcherPath = productDir();

# Check to see that all the frameworks are built.
checkFrameworks();

# Set paths according to the build system used
if (isQt()) {
    my $libDir = catdir(productDir(), 'lib');
    if (isWK2()) {
        $launcherPath = catdir($launcherPath, "bin", "MiniBrowser");
    } else {
        $launcherPath = catdir($launcherPath, "bin", "QtTestBrowser");
    }

    $ENV{QTWEBKIT_PLUGIN_PATH} = catdir($libDir, 'plugins');

    print "Starting webkit launcher, running against the built WebKit in $libDir...\n";
    if (isDarwin()) {
        $ENV{DYLD_LIBRARY_PATH} = $ENV{DYLD_LIBRARY_PATH} ? "$libDir:$ENV{DYLD_LIBRARY_PATH}" : $libDir;
        $ENV{DYLD_FRAMEWORK_PATH} = $ENV{DYLD_FRAMEWORK_PATH} ? "$libDir:$ENV{DYLD_FRAMEWORK_PATH}" : $libDir;
    } else {
        $ENV{LD_LIBRARY_PATH} = $ENV{LD_LIBRARY_PATH} ? "$libDir:$ENV{LD_LIBRARY_PATH}" : $libDir;
    }
} else {

    if (isGtk()) {
        if (isWK2()) {
            unshift(@ARGV, catdir($launcherPath, "Programs", "MiniBrowser"));
        } else {
            unshift(@ARGV, catdir($launcherPath, "Programs", "GtkLauncher"));
        }
        $launcherPath = catdir(sourceDir(), "Tools", "jhbuild", "jhbuild-wrapper");
        unshift(@ARGV, ("--gtk", "run"));
    }

    if (isEfl()) {
        if (isWK2()) {
            unshift(@ARGV, catdir($launcherPath, "bin", "MiniBrowser"));
        } else {
            unshift(@ARGV, catdir($launcherPath, "bin", "EWebLauncher"));
        }
        $launcherPath = catdir(sourceDir(), "Tools", "jhbuild", "jhbuild-wrapper");
        unshift(@ARGV, ("--efl", "run"));
    }

    print "Starting webkit launcher.\n";
}

exec $launcherPath, @ARGV or die;

