#!/usr/bin/perl

# Copyright (C) 2006 Apple Computer, Inc.  All rights reserved.
#
# Redistribution and use in source and binary forms, with or without
# modification, are permitted provided that the following conditions
# are met:
#
# 1.  Redistributions of source code must retain the above copyright
#     notice, this list of conditions and the following disclaimer.
# 2.  Redistributions in binary form must reproduce the above copyright
#     notice, this list of conditions and the following disclaimer in the
#     documentation and/or other materials provided with the distribution.
# 3.  Neither the name of Apple Computer, Inc. ("Apple") nor the names of
#     its contributors may be used to endorse or promote products derived
#     from this software without specific prior written permission.
#
# THIS SOFTWARE IS PROVIDED BY APPLE AND ITS CONTRIBUTORS "AS IS" AND ANY
# EXPRESS OR IMPLIED WARRANTIES, INCLUDING, BUT NOT LIMITED TO, THE IMPLIED
# WARRANTIES OF MERCHANTABILITY AND FITNESS FOR A PARTICULAR PURPOSE ARE
# DISCLAIMED. IN NO EVENT SHALL APPLE OR ITS CONTRIBUTORS BE LIABLE FOR ANY
# DIRECT, INDIRECT, INCIDENTAL, SPECIAL, EXEMPLARY, OR CONSEQUENTIAL DAMAGES
# (INCLUDING, BUT NOT LIMITED TO, PROCUREMENT OF SUBSTITUTE GOODS OR SERVICES;
# LOSS OF USE, DATA, OR PROFITS; OR BUSINESS INTERRUPTION) HOWEVER CAUSED AND
# ON ANY THEORY OF LIABILITY, WHETHER IN CONTRACT, STRICT LIABILITY, OR TORT
# (INCLUDING NEGLIGENCE OR OTHERWISE) ARISING IN ANY WAY OUT OF THE USE OF
# THIS SOFTWARE, EVEN IF ADVISED OF THE POSSIBILITY OF SUCH DAMAGE.

# This script runs a list of scripts through jsc a specified number of times.

use strict;
use warnings;
use File::Spec;
use FindBin;
use lib $FindBin::Bin;
use Getopt::Long;
use webkitdirs;

my $usage = "Usage: run-jsc [--count run_count] [--verbose] shell_file [file2...]";

my $count = 1;
my $verbose = 0;
GetOptions("count|c=i" => \$count,
           "verbose|v" => \$verbose);

my $jsc = jscProductDir() . "/jsc @ARGV";
$jsc .= " 2> " . File::Spec->devnull() unless $verbose;

my $dyld = jscProductDir();

$ENV{"DYLD_FRAMEWORK_PATH"} = $dyld;
print STDERR "Running $count time(s): DYLD_FRAMEWORK_PATH=$dyld $jsc\n";
while ($count--) {
    if (system("$jsc") != 0) {
        last;
    }
}

