/*
 * Copyright (C) 2006 Samuel Weinig <sam.weinig@gmail.com>
 * Copyright (C) 2006, 2009 Apple Inc. All rights reserved.
 *
 * Redistribution and use in source and binary forms, with or without
 * modification, are permitted provided that the following conditions
 * are met:
 * 1. Redistributions of source code must retain the above copyright
 *    notice, this list of conditions and the following disclaimer.
 * 2. Redistributions in binary form must reproduce the above copyright
 *    notice, this list of conditions and the following disclaimer in the
 *    documentation and/or other materials provided with the distribution.
 *
 * THIS SOFTWARE IS PROVIDED BY APPLE INC. ``AS IS'' AND ANY
 * EXPRESS OR IMPLIED WARRANTIES, INCLUDING, BUT NOT LIMITED TO, THE
 * IMPLIED WARRANTIES OF MERCHANTABILITY AND FITNESS FOR A PARTICULAR
 * PURPOSE ARE DISCLAIMED.  IN NO EVENT SHALL APPLE INC. OR
 * CONTRIBUTORS BE LIABLE FOR ANY DIRECT, INDIRECT, INCIDENTAL, SPECIAL,
 * EXEMPLARY, OR CONSEQUENTIAL DAMAGES (INCLUDING, BUT NOT LIMITED TO,
 * PROCUREMENT OF SUBSTITUTE GOODS OR SERVICES; LOSS OF USE, DATA, OR
 * PROFITS; OR BUSINESS INTERRUPTION) HOWEVER CAUSED AND ON ANY THEORY
 * OF LIABILITY, WHETHER IN CONTRACT, STRICT LIABILITY, OR TORT
 * (INCLUDING NEGLIGENCE OR OTHERWISE) ARISING IN ANY WAY OUT OF THE USE
 * OF THIS SOFTWARE, EVEN IF ADVISED OF THE POSSIBILITY OF SUCH DAMAGE. 
 */

[
    Conditional=SVG,
    CustomToJSObject,
    ObjCPolymorphic,
    ImplementationLacksVTable
] interface SVGPathSeg {
    // Path Segment Types
    const unsigned short PATHSEG_UNKNOWN = 0;
    const unsigned short PATHSEG_CLOSEPATH = 1;
    const unsigned short PATHSEG_MOVETO_ABS = 2;
    const unsigned short PATHSEG_MOVETO_REL = 3;
    const unsigned short PATHSEG_LINETO_ABS = 4;
    const unsigned short PATHSEG_LINETO_REL = 5;
    const unsigned short PATHSEG_CURVETO_CUBIC_ABS = 6;
    const unsigned short PATHSEG_CURVETO_CUBIC_REL = 7;
    const unsigned short PATHSEG_CURVETO_QUADRATIC_ABS = 8;
    const unsigned short PATHSEG_CURVETO_QUADRATIC_REL = 9;
    const unsigned short PATHSEG_ARC_ABS = 10;
    const unsigned short PATHSEG_ARC_REL = 11;
    const unsigned short PATHSEG_LINETO_HORIZONTAL_ABS = 12;
    const unsigned short PATHSEG_LINETO_HORIZONTAL_REL = 13;
    const unsigned short PATHSEG_LINETO_VERTICAL_ABS = 14;
    const unsigned short PATHSEG_LINETO_VERTICAL_REL = 15;
    const unsigned short PATHSEG_CURVETO_CUBIC_SMOOTH_ABS = 16;
    const unsigned short PATHSEG_CURVETO_CUBIC_SMOOTH_REL = 17;
    const unsigned short PATHSEG_CURVETO_QUADRATIC_SMOOTH_ABS = 18;
    const unsigned short PATHSEG_CURVETO_QUADRATIC_SMOOTH_REL = 19;

    readonly attribute unsigned short pathSegType;
    readonly attribute DOMString pathSegTypeAsLetter;
};

