set(IMAGE_DIFF_SOURCES
    ${IMAGE_DIFF_DIR}/efl/ImageDiff.cpp
)

list(APPEND IMAGE_DIFF_INCLUDE_DIRECTORIES
    ${ECORE_EVAS_INCLUDE_DIRS}
    ${ECORE_INCLUDE_DIRS}
    ${EINA_INCLUDE_DIRS}
    ${EO_INCLUDE_DIRS}
    ${EVAS_INCLUDE_DIRS}
)

list(APPEND IMAGE_DIFF_LIBRARIES
    ${ECORE_EVAS_LIBRARIES}
    ${ECORE_LIBRARIES}
    ${EINA_LIBRARIES}
    ${EO_LIBRARIES}
    ${EVAS_LIBRARIES}
)
